Repository anasjawed283/KR260-AMD-SoftwareTesting, pull requests merged in 2024-07, with the labels that each got.

#1 extract feature in machine vision folder
  Machine Vision/Object_Feature_Extraction.py
Labels: enhancement

#2 add Grip_Force_Control.py
  Machine Vision/Grip_Force_Control.py
Labels: enhancement

#3 AI_MODEL (optional update)
  Machine Vision/AI_Model.py
Labels: good first issue

#4 How to connect (Readme Update)
  README.md
Labels: documentation
